### ISSUE TITLE
Link to real stars

### ISSUE THREAD

**Issue by SamMackrill** [themroc5/eddb.io#10]
Many systems are real stars, would be nice if we could link them to wikipedia and/or a star catalog

e.g.
WISE 1506+7027
http://ross.eddb.io/system/update/19047
https://en.wikipedia.org/wiki/WISE_1506+7027
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=EQ+J1506%2B7027

**Comment by themroc5** [comment]
An automated system would be great. any idea how to get a proper simbad reference? I'm not too much into this to know...

**Comment by Mikayex** [comment]
Links to Simbad has been added.
Now I'm working on linking with Wikipedia...

**Comment by themroc5** [comment]
https://en.wikipedia.org/w/api.php

**Comment by Mikayex** [comment]
I know about this api and also [wikidata](https://www.wikidata.org/wiki/Wikidata:Data_access) could be useful to make sure this is a star...

**Comment by themroc5** [comment]
that looks good!
