### ISSUE TITLE
Link to "Element Material Logger" from "Create Body"

### ISSUE THREAD

**Issue by mwerle** [themroc5/eddb.io#103]
Forward and backward links between the "Element Material Logger" and "Create Body" pages.

Also, link to the EML from the System/Bodies list.

The "Back" button on the EML should return to the page which called it - currently it returns to a list.

**Comment by themroc5** [comment]
The Logger will die instantly once 2.2 drops, since the Journal will provide more detailed data. Sorry, not fixing :)
