### ISSUE TITLE
Verification email not working (Bad request (#400)) halp

### ISSUE THREAD

**Issue by ieatass** [themroc5/eddb.io#107]
When clicking on my verification email, its sends me to a page saying:

Bad Request (#400)

Wrong token.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

Plz help

**Comment by themroc5** [comment]
That means that somebody (man or machine) did visit the link already. Could be precaching of your browser. 

In the end, you're activated now. So simply log in :)

**Comment by ieatass** [comment]
Thanks man didn't even try to log in
