### ISSUE TITLE
Wrong intel on prices

### ISSUE THREAD

**Issue by madosoft65** [themroc5/eddb.io#108]
Iben Hub   Iota Hydri  
61.30 ly
 Curtiss Port   Caledo  
Pad: L  1,132 ls  15 hours
Pad: L  1,002 ls  23 hours
Buy for 15,890 Cr Supply: 9,163
350 ×  Imperial Slaves
Demand: 94,649 Sell for 16,953 Cr
Profit: 1,063 Cr/t 372,050 Cr

Actually price i get is : 15.678 Cr

??????

**Comment by Marginal** [comment]
Prices can change, particularly in systems near the centre with high traffic.

You an do your bit to keep prices up to date by running an app like [E:D Market Connector](https://github.com/Marginal/EDMarketConnector/wiki).

**Comment by themroc5** [comment]
You heard the man :) EDDB is 100% community driven. There is no magic channel from Frontier. It's up to the community how accurate EDDB eventually is.

Here you can find more information too: https://ross.eddb.io/faq
