### ISSUE TITLE
Suggestion for smarter faction system sort

### ISSUE THREAD

**Issue by freiheit** [themroc5/eddb.io#114]
On the faction information page ( like https://eddb.io/faction/11217 ), it seems that the sort order is alphabetical.

The Home System should really be the first one listed.

Also, I think either distance from Home System or population would be more useful ordering than alphabetical. (distance from Home System would let the Home System not be special cased, since "0" should always be first). Maybe a sort fallback to alphabetical if distance or population is the same.

Related to #113

**Comment by themroc5** [comment]
done
