### ISSUE TITLE
planetary settlements size is missing in stations.jsonl

### ISSUE THREAD

**Issue by cold-n-sour** [themroc5/eddb.io#117]
For planetary settlements, there is no data in the dumps to determine the size (+, ++, +++)

**Comment by cold-n-sour** [comment]
Also it would be beneficial to include the security level for planetary settlements

**Comment by themroc5** [comment]
I don't have the security level in EDDB.

**Comment by cold-n-sour** [comment]
I know. That's why I'm asking to consider adding it, if at all possible :)
