### ISSUE TITLE
When Station Deleted, show who/what created it

### ISSUE THREAD

**Issue by seeebek** [themroc5/eddb.io#12]
I would really like to see who or what created a station which was deleted. I mean especially which tool uploaded commodities data and created the wrong station name. 
Example of Database Change History:
4 hours  |  seeebek  |  Roosa H 'U 'B  |  Delete  |  ID->11869   System->14795   Name->Roosa H 'U 'B   Has Commodities->Yes   Created By-> EDDN (EliteOCR 0.3.8 id: EOb00b1234)

This would help greatly to understand where the really bad station names come from.

**Comment by themroc5** [comment]
Roosa H 'U 'B: EliteOCR 0.5.2.3
Ford Tfriviinai: RegulatedNoise 1.84
Pr U Nari U Laboratory: EliteOCR 0.5.2.3
Ti-Ohnton Hub: EliteOCR 0.5.2.3
Piehe.Y Gateway: EliteOCR 0.5.2.3
Chiao Àding: EliteOCR 0.5.2.3
Sudvvor'ieu Orbital: RegulatedNoise 1.84
Bulgafiin Oocte: RegulatedNoise 1.84

seems to be just those two for the last entries..

**Comment by seeebek** [comment]
It's almost as those were posted by purpose. There is nothing I can do to prevent it...

**Comment by themroc5** [comment]
as long as we have an active community, those wrong ones just get purged :+1:
