### ISSUE TITLE
Duplicate system entry

### ISSUE THREAD

**Issue by dan-masek** [themroc5/eddb.io#129]
Not sure whether this is the proper place to report data issues, but I didn't find a way how to deal with this in ROSS.

I've just ran across the following two entries:
* "Synuefe GY-U b21-0" https://eddb.io/system/182011
* "Synuefe GY-U b21-0," (extra comma at the end) https://eddb.io/system/95508

Positions match, the EDSM links differ (the one from id 182011 is good).

**Comment by themroc5** [comment]
Thx! Deleted. Next time you can report it on our Discord. Maybe easier than opening an issue everytime :)
