### ISSUE TITLE
Add updatecount to api

### ISSUE THREAD

**Issue by Jengall** [themroc5/eddb.io#13]
Plz could you add the UpdateCount  on commodities to the stations.json api file.
 :)

**Comment by themroc5** [comment]
will be in v3 of the dump

**Comment by themroc5** [comment]
sorry for the reopening hazzle

**Comment by Jengall** [comment]
np,
thx for the update :)

2015-03-15 16:15 GMT+01:00 themroc5 <notifications@github.com>:
