### ISSUE TITLE
Upcoming system name changes

### ISSUE THREAD

**Issue by CMDR-Cometborne** [themroc5/eddb.io#136]
The following system name changes happened in Colonia in the 2.4 beta:

Credit: Ian's Colonia Database via Wishblend in the ccn discord #announcement channel
Wishblend (CCL314) - Today at 7:43 AM
BETA system renames, these names are not in the game yet (only beta) but when 2.4 goes fully live they wll be
System Renames 
Eol Prou MW-L c8-16 => Poe
Eol Prou VY-R d4-49 => White Sun
Eol Prou PC-K c9-107 => Chrysus
Eol Prou RS-T d3-46 => Juniper
Eol Prou LW-L c8-83 => Rodentia
Eol Prou IW-W e1-3046 => Kajuku
Eol Prou IW-W e1-1696 => Lycanthrope
Ratri => Ratraii
Ogma => Ogmar
Eol Prou IW-W e1-973 => Farwell
Eol Prou UN-W b17-5 => Carlota
Eol Prou PX-T d3-122 => Morpheus
Eol Prou TD-S d4-60 => Earth Expeditionary Fleet
Eol Prou LW-L c8-211 => Centralis
Thanks to Ian's Colonia Database

**Comment by themroc5** [comment]
Will you simply rename them while ED is down due to the 2.4 switch? (Whenever this is?)
