### ISSUE TITLE
Supply quantities in commodities show value of 0

### ISSUE THREAD

**Issue by VonSpicyWiener** [themroc5/eddb.io#139]
Good day sir/ma'am 

This ticket is in regards to the supply value in the commodities tab is showing a constant 0

Thank you.
CMDR Von

**Comment by themroc5** [comment]
What station? The first I picked has some supplies: https://eddb.io/station/market/18

**Comment by VonSpicyWiener** [comment]
Hey thanks for getting back to me, I have attached some screen shots of the
issue I'm having, I'm looking to trade specifically palladium and it's
showing top stations as 0 in supply. Hopefully this will help clarify what
is causing this for me.

Thank you
CMDR Von

**Comment by themroc5** [comment]
I can see no screenshots...

**Comment by VonSpicyWiener** [comment]
They're not attaching properly, here's the link https://eddb.io/commodity/45

**Comment by themroc5** [comment]
Palladium can only be mined and no station sells it directly. No bug here...

**Comment by VonSpicyWiener** [comment]
That must be a new thing in 2.4 you could buy palladium before

**Comment by themroc5** [comment]
I was wrong! I'll look into it

**Comment by VonSpicyWiener** [comment]
Ok, Thank you

**Comment by themroc5** [comment]
That was only the tip of the iceberg. While pointing this out (and sticking to it) we discovered a much bigger flaw on EDDB and successfully fixed it :) I had to remove ~ 30k wrong prices. 

Thanks!

**Comment by VonSpicyWiener** [comment]
Wow! Thank you for fixing this issue!
