### ISSUE TITLE
Trend of Prices

### ISSUE THREAD

**Issue by nyansen** [themroc5/eddb.io#14]
example:
Fish - last price 134; new price 128 - Trend down
Gold - last price 9456; new price 10145 - Trend up

And a Stat. will be nice. To see the Trend from the last x month

**Comment by Telemicus** [comment]
I have actually considered doing this myself based on EDDB's data. I've already started importing EDDB's data on a daily basis in order to look at the trends but I don't have a hosted version at the moment.

**Comment by themroc5** [comment]
The database is not built to deliver this kind of information in real time with a reasonable performance.
