### ISSUE TITLE
Commodities tab not showing correct amount of supply

### ISSUE THREAD

**Issue by VonSpicyWiener** [themroc5/eddb.io#140]
Hey I contacted you yesterday with regards to this, you said palladium is only mieable and there is no issue. I think you were thinking of Platnium, regardless this issue is happening with gold as well, seems like it affects the metals mostly. Now when I go into the single hop tab I am getting routes that have Palladium with supplies of 100,000+ at an age of less than 2 days, It seems like the commodities tab and single hop tab are using two different data points.

Thanks.
CMDR Von.

**Comment by themroc5** [comment]
see #139
