### ISSUE TITLE
Loop Route Finder

### ISSUE THREAD

**Issue by jkurittu** [themroc5/eddb.io#141]
Hi

Would it be possible to limit the area of search for the loop route finder when needed only local trading. For example when in Colonia it would be very good to be able to identify best loop routes in and around Colonia.

Thanks
Jari

**Comment by themroc5** [comment]
Why not simply sort by distance to your reference system?

**Comment by jkurittu** [comment]
Because that would exclude the most profitable trade route and the point of the loop finder, to my understanding, to find the most profitable trade routes but when you are in Colonia the most profitable routes are over 22000 ly away and therefore it could be nice to be have the option to say e.g. max 300 ly from reference system. Currently the loop route finder asks for your reference system but for no real reason as it only lists the best routes independently of the distance.

Alternatively it would be nice to have a Colonia dedicated route finder.
