### ISSUE TITLE
Why did you cut off the distance?

### ISSUE THREAD

**Issue by Batonseven** [themroc5/eddb.io#145]
![2018-01-30_19-29-08](https://user-images.githubusercontent.com/35968245/35578412-0ac7828a-05f5-11e8-9783-f39b9eab40ac.png)
Now I can not find a planet with the highest gravity in the galaxy (((

**Comment by AnthorNet** [comment]
This can be pretty intensive, that said EDSM has a lot of records available, feel fre to raise an issue for gravity to be added!

https://www.edsm.net/en/statistics/bodies

**Comment by Batonseven** [comment]
I did not find there a filter of planets with the possibility of landing and the choice of characteristics such as gravity, distance from the star. It seems to have never before been this limit of 100 light years

**Comment by themroc5** [comment]
I had to limit the search distance due to a massive CPU inbalance. Only 5% of the users used the body search but took 90+% CPU time. Now it's much more reasonable. Sorry but there is no other way at the moment.
