### ISSUE TITLE
Use "Collected_at" value in listings.csv

### ISSUE THREAD

**Issue by JLPicard2111** [themroc5/eddb.io#146]
Hey guys,

I'm currently doing some experiment regarding visualizing the data provided by eddb.. So far I've downloaded the .json and .csv files provided on that page and used Tableau to start building some reports out of that. However I can't do any analysis over time because the "collected_at" value (file: Listings.csv) is some kind of weird number which I can't translate back to a proper datetime value.

Is there anybody who can assist here?

**Comment by AnthorNet** [comment]
Should be a standard Unix timestamp.

**Comment by JLPicard2111** [comment]
Thanks.. that helped already. Now I know what to google and I already found a calculation to convert it into a standard datetime value. :)
