### ISSUE TITLE
Timestamp on Station changes

### ISSUE THREAD

**Issue by maddavo** [themroc5/eddb.io#15]
Pls add a UTC timestamp to station.json and station_lite.json files to represent the time when a station was last modified.  In the TD Station.csv file the field is called "modified", but any appropriate label will do.

**Comment by themroc5** [comment]
the field is gonna be called updated_at

**Comment by maddavo** [comment]
Great tks.  I'll make preparations.

**Comment by maddavo** [comment]
Hi, any progress on this?

**Comment by themroc5** [comment]
fixed. will be in v3
