### ISSUE TITLE
Feature Request: dark mode

### ISSUE THREAD

**Issue by JimLindsey** [themroc5/eddb.io#152]
Would be a lot easier on this old man's eyes if there was an easy way to toggle a dark mode or a color theme similar to EDSM.  
 (Thank you for all your donated time and effort )

**Comment by vovchisko** [comment]
Can I help?

**Comment by Rimhollow** [comment]
I would also love to see this!

I'm currently using the Stylish browser extension, for which EDDB skins can be found [here](https://userstyles.org/styles/browse?search_terms=eddb&type=false), but not everyone knows about that or wants to install it. I frequently tab back and forth EDDB to the darkness of Elite, so it's a big help to make it darker.

**Comment by JimLindsey** [comment]
Thanks, good idea; sometimes can't see the forest because of the trees.

**Comment by ahin4114** [comment]
Should this now be closed?

**Comment by themroc5** [comment]
Indeed!
