### ISSUE TITLE
Bug: empty hop suppresses superior loops in loopfinder

### ISSUE THREAD

**Issue by Clavis0** [themroc5/eddb.io#155]
Loop finder ignores loop that have no return good.

Right now there are several loops where you could earn 13+k/ton for military fabrics, with an empty return flight. Loop finder ignores all of these, and shows the best available loop at 11k/roundtrip. 

(reference place is beta trianguli australis). These loops were shown earlier today, with scrap as return fright, but as people worked them the "scrap" return fright was depleted.  But still even with empty return those loops beat everything else within reach. So Loopfinder should show hem.

**Comment by themroc5** [comment]
That is unfortunate indeed. The whole mechanism is built to only work with 2 hauls at the moment and to change that I'd need time, which I do not have at the moment :/
