### ISSUE TITLE
Feature Request: Ship prices

### ISSUE THREAD

**Issue by Bellaby** [themroc5/eddb.io#162]
It would be nice to see the price of a ship being sold in the station.

I'm trying to figure out how much credits I need for a ship and it'd be pretty handy seeing the price when I look at the station's details.

Not sure if ship prices differ per station or system but still it would be handy.

Thanks!

**Comment by themroc5** [comment]
The price can indeed vary considerably. So I let the site Coriolis (https://coriolis.io/) take 100% care of that topic ;)
