### ISSUE TITLE
Search bar requires >1 characters even though it says "Please enter 1 or more character"

### ISSUE THREAD

**Issue by lazho** [themroc5/eddb.io#164]
Title. Discovered when searching for a system named "h". (Yes, it is real.) Currently you can circumvent this by adding a space after the 1st character to trigger the search.

Should be a quick fix :)

### Screenshot
![image](https://user-images.githubusercontent.com/2417212/84538493-bc884680-acbf-11ea-8099-70efb3cec1d5.png)

**Comment by themroc5** [comment]
It means "From now on, enter 1 or more characters to match the least of 2 since you entered one already". Makes sense?

The reason the limit is 2, to decrease server load. So I rather leave it as is and let the "insiders" use spaces for "h" ;)
