### ISSUE TITLE
Maximum sell price for Alexandrite is permanently stuck at 1000% market average

### ISSUE THREAD

**Issue by mgschwenk** [themroc5/eddb.io#166]
Noticed this for a few days now, the price is the exact amount one could set at their carrier market and doesn't reflect the actual max sell price:
![image](https://user-images.githubusercontent.com/64966460/85955808-9f22d000-b981-11ea-8860-679b2db7dfb0.png)

**Comment by themroc5** [comment]
Indeed it was broken. Just deployed a fix...
