### ISSUE TITLE
Single hop route no fixed destination

### ISSUE THREAD

**Issue by sword134** [themroc5/eddb.io#168]
Hello, I was wondering why the single route finder requires a fixed destination? This is not the case on another website and it kind of defeats the purpose of the autotrading website.

**Comment by themroc5** [comment]
It needs a fixed origin location OR a destination location. It is no "best price in the universe" helper but a "I am here or want to go there" helper. If you need the best of the best, try the ^Loop Finder: https://eddb.io/trade/loops
