### ISSUE TITLE
Feature request: search function - commodities

### ISSUE THREAD

**Issue by WaywardGoat** [themroc5/eddb.io#169]
I think a search function on the commodities list will be very helpful, there is a lot of commodities and I think it'll make searching for a specific one much much faster.

**Comment by tfricks** [comment]
@WaywardGoat 

In case you didn't know, CTRL+F will open a text search box on most browsers. Probably COMMAND+F on mac.

**Comment by WaywardGoat** [comment]
> @WaywardGoat
> 
> In case you didn't know, CTRL+F will open a text search box on most browsers. Probably COMMAND+F on mac.

I know, just thought an official feature would be useful for those who are unaware of being able to do that.

**Comment by tfricks** [comment]
> > @WaywardGoat
> > In case you didn't know, CTRL+F will open a text search box on most browsers. Probably COMMAND+F on mac.
> 
> I know, just thought an official feature would be useful for those who are unaware of being able to do that.

Sure, not discounting your request. Just thought I'd point it out in case you didn't know. I didn't want you to wait for this to be implemented to have almost the same feature. I don't, in any way, speak for the project.

Have a nice rest of your day :)

**Comment by WaywardGoat** [comment]
> > > @WaywardGoat
> > > In case you didn't know, CTRL+F will open a text search box on most browsers. Probably COMMAND+F on mac.
> > 
> > 
> > I know, just thought an official feature would be useful for those who are unaware of being able to do that.
> 
> Sure, not discounting your request. Just thought I'd point it out in case you didn't know. I didn't want you to wait for this to be implemented to have almost the same feature. I don't, in any way, speak for the project.
> 
> Have a nice rest of your day :)

Yeah I understand, thanks for the thought :) Sorry for late reply.

You too. :)

**Comment by themroc5** [comment]
I rather keep it as it is since Ctrl+F is universally known (most of the time) and I rather not spend the time to write a feature which comes in a browser already.

**Comment by WaywardGoat** [comment]
> I rather keep it as it is since Ctrl+F is universally known (most of the time) and I rather not spend the time to write a feature which comes in a browser already.

Fair enough, thanks for the response. :)
