### ISSUE TITLE
Station rename Hanger==>Hangar

### ISSUE THREAD

**Issue by SamMackrill** [themroc5/eddb.io#17]
Any station ending in " Hanger" has been renamed in game to " Hangar"
This is a valid spelling fix.

**Comment by maddavo** [comment]
I don't think that is the case.  Looking through many systems it seems that there are stations that have "Hanger" and stations that have "Hangar" - so both appear to be in-game.  Although I did see a station that changed spelling between versions at some stage.

**Comment by themroc5** [comment]
Now I'm confused :)

**Comment by SamMackrill** [comment]
OK I there are about 200 XXXX Hangar stations in EDDB. I have made a random sample of 15 of them and they are all now spelled XXXX Hanger in game when they were definitely Hanger before the update. Could you backup your claim with some hard evidence please?

**Comment by maddavo** [comment]
Sam, I appreciate you want to get data correct and I encourage that.  I am a little taken aback by the manner in which you are expressing yourself - particularly asking me to 'backup my claim' which seems a bit agressive.  I note you admit you only took a random sample.  Surely this would be a case where you would be needing to prove your initial assertion (by comprehensive data) rather than I proving the negative.

Nevertheless, I will assist.  I maintain a list of 13k+ stations.  I have done a search of that list and there are 100 "Hanger" stations and 18 "Hangar" stations.  I agree that "Hanger" is far more common (and explains the plausibility of your random sample only giving the "Hanger" spelling), but I disagree that "Hangar" no longer exists.

Of the 18 "Hangar" stations, I have personally checked 6 of them - they are:
APOYAS/Bliss Hangar        (Verified)
FLOUSOP/Bosch Hangar       (Verified)
LHS 2335/Haberlandt Hangar  (Verified)
LTT 15985/Akiyama Hangar    (Verified)
LUNG/Qureshi Hangar         (Verified)
SIFJAR/Graham Hangar        (Verified)
The existence of these stations disproves the initial assertion.

The remaining 12 "Hangar" stations in my station list are:
ATJIRAJAN/Sakers Hangar
AUSCABS/Fulton Hangar      
BD+05 5244/Hoshi Hangar
CHAKMO/Kornbluth Hangar
G 30-26/Boltzmann Hangar
KIRRAE/Kneale Hangar
LHS 2166/Veach Hangar
LTT 17868/Pierce Hangar
NAURACOTA/Silves Hangar
SHANLUO ZI/Fincke Hangar
UNDADJA/McArthur Hangar
WOLF 1182/Clifton Hangar
I do not have system view access to those systems so I invite you or others to verify those.  However the subsequent verification of these is not necessary to disprove the initial assertion.

**Comment by maddavo** [comment]
The list I have of "Hanger" stations is:
110 HERCULIS/Jahn Hanger
ACKWADA/Carter Hanger
AG+21 1754/Oleskiw Hanger
ANINOHANU/Bardeen Hanger
ANSUZ/Marconi Hanger
APSU/Dickinson Hanger
AWAWAD/Bosch Hanger
BASIKA/Bohm Hanger
BD-07 4419/Hale Hanger
BD-09 4592/Tsunenaga Hanger
BHUMBI/Westphal Hanger
BIFROST/Godwin Hanger
CAMBOU/Musabayev Hanger
CHAKMO/Kornbluth Hanger
CHANGTHINI/Shkaplerov Hanger
CHAYANSI/Bernoulli Hanger
CHIH ZHA/Hinz Hanger
CLOTTI/O'Connor Hanger
COELRIND/Siegel Hanger
COLLANGBAKA/Pennington Hanger
COQUI XEE/Durrance Hanger
CPO 24/Grabe Hanger
DAIKULCANDI/Chretien Oudemans Hanger
DJEDET/Linnaeus Hanger
FIRDAUS/Bernoulli Hanger
G 113-20/Ansari Hanger
GCRV 62586/Peary Hanger
GEORGE PANTAZIS/Melvin Hanger
GLIESE 875/Wilson Hanger
GLUTIA/Windt Hanger
GYVATI/Skolem Hanger
HIP 68107/Potrykus Hanger
HIP 77310/Grabe Hanger
HOLVAIT/Nikolayev Hanger
HSIEN BAJI/Strekalov Hanger
INGGUROMAL/Cogswell Hanger
JAITU/Wetherbee Hanger
JEMETANI/Lovelace Hanger
JUIQUAN/Hurston Hanger
KAMCHANDIKA/Burnham Hanger
KATANING/Dalgarno Hanger
KIPSIGINES/Sellers Hanger
KUNGKALIS/Struve Hanger
KUNGUN/Lowell Hanger
KUSHAMBO/Suntzeff Hanger
L 258-146/Mendeleev Hanger
LFT 1504/Eyharts Hanger
LHS 2166/Veach Hanger
LHS 2335/Haberlandt Hanger
LHS 3246/Hertz Hanger
LHS 3746/Reisman Hanger
LHS 64/Wiberg Hanger
LOSIN/Ivanchenkov Hanger
LP 329-20/Guest Hanger
LP 48-567/Noakes Hanger
LP 576-34/Curbeam Hanger
LP 69-457/Mendeleev Hanger
LP 716-35/Tyurin Hanger
LP 862-184/Mayr Hanger
LP 90-39/Hermite Hanger
LTT 15985/Akiyama Hanger
LTT 17868/Pierce Hanger
LTT 305/Lefschetz Hanger
LUNG/Qureshi Hanger
MOORTIC/DeLucas Hanger
MU ARAE/Herreshoff Hanger
MURIGES/Scully-Power Hanger
NED ERH/Polyakov Hanger
NGURELBAN/Duke Hanger
NU-1 LUPI/Skripochka Hanger
NUNET/Gardner Hanger
OXLAHUNTIKU/Linge Hanger
PA PARA/Ayerdhal Hanger
PAEMALITES/Wankel Hanger
PARIBELA/Ito Hanger
PETRA/Oshima Hanger
RAJUKRU/Nicollier Hanger
ROSS 128/Galton Hanger
SHANLUO ZI/Fincke Hanger
SHASIL/Kawasato Hanger
SUMMERLAND/Henry O'Hare's Hanger
SWAZAKAN/Haisheng Hanger
T TIE/Sukhoi Hanger
TAURAWA/Benyovszky Hanger
TAWARET/Lilienthal Hanger
THEOTOKOS/Spring Hanger
TIANNODAABE/Carver Hanger
UALAME/Lessing Hanger
UNDADJA/McArthur Hanger
UTSE/Whitworth Hanger
V816 HERCULIS/Hobaugh Hanger
VIRUD/Beadle Hanger
WOLF 1060/Pawelczyk Hanger
WOLF 1182/Clifton Hanger
WUNJO/Baudin Hanger
XUCURI/Al-Farabi Hanger
ZEESSZE/Nicollier Hanger
ZHANGDA/Tennyson D'Eyncourt Hanger
ZHI/Lister Hanger
ZUGEN/Soddy Hanger

Interestingly, the first station has changed to "Hangar" as you say.  But the 2nd station in ACKWADA I have verified and is spelt "Hanger" so this disproves that all of them are changed to either Hanger or Hangar - there are definitely both in-game.

**Comment by maddavo** [comment]
I have gone through the "Hanger" list and checked the following in-game:
110 HERCULIS/Jahn Hanger       Hangar
ACKWADA/Carter Hanger          VERIFIED
AWAWAD/Bosch Hanger            Hangar
CHANGTHINI/Shkaplerov Hanger   Hangar
COELRIND/Siegel Hanger         DELETED
COLLANGBAKA/Pennington Hanger  Hangar
COQUI XEE/Durrance Hanger      Hangar
DAIKULCANDI/Chretien Oudemans  Hanger
FIRDAUS/Bernoulli Hanger       Hangar
GCRV 62586/Peary Hanger        Hangar
GEORGE PANTAZIS/Melvin Hanger  Hangar
KIPSIGINES/Sellers Hanger      Hangar
L 258-146/Mendeleev Hanger     Hangar
LHS 2335/Haberlandt Hanger     Hangar
LHS 64/Wiberg Hanger           Hangar
LP 329-20/Guest Hanger         Hangar
LP 69-457/Mendeleev Hanger     DELETED
LP 716-35/Tyurin Hanger        Hangar
LTT 15985/Akiyama Hanger       Hangar
LTT 305/Lefschetz Hanger       Hangar
LUNG/Qureshi Hanger            Hangar
PA PARA/Ayerdhal Hanger        Hangar
PETRA/Oshima Hanger            Hangar
RAJUKRU/Nicollier Hanger       DELETED
ROSS 128/Galton Hanger         Hangar
SUMMERLAND/Henry O'Hare's Hanger    VERIFIED
THEOTOKOS/Spring Hanger         Hangar
UALAME/Lessing Hanger           Hangar
V816 HERCULIS/Hobaugh Hanger    Hangar
WOLF 1060/Pawelczyk Hanger      Hangar
XUCURI/Al-Farabi Hanger         Hangar
ZEESSZE/Nicollier Hanger        VERIFIED
ZHI/Lister Hanger               Hangar

I cannot see the system view for the remainder.  If others could to the same to check and list the results then we can collectively get the data right.

**Comment by SamMackrill** [comment]
Hmmm sorry if I sounded aggressive I certainly didn't mean to be especially over something so trivial! And I did say please :) looks like not enough emotes :p All I really wanted was a couple of examples of stations in game that were still spelled Hanger. I think there may be some massive confusion here.

I put in a ticket weeks ago to FD about this spelling error and it looks like they finally took some action, however I am quite prepared to admit I am mistaken or they only did a half way job.

I was careful to check in game that the auto-generated names used Hanger before I submitted the ticket and I have check twice in game that they seem to be corrected to Hangar now.

If there are any "Hangers" left in game they should be brought to FD's attention.

I will have a look in game at your list later, thanks.

Peace!

**Comment by SamMackrill** [comment]
Ok I have been through your Hanger list in game, you can search on Station Name so it is easy, if a little tedious, to check them all.

It is clear that FD have renamed all the autogenerated stations ending in Hanger

They missed a few of the hand crafted systems as you found:

ACKWADA/Carter Hanger
SUMMERLAND/Henry O'Hare's Hanger
ZEESSZE/Nicollier Hanger

Can't see any others above these 3.
I will put in a bug post

Cheers!

**Comment by themroc5** [comment]
ok, I fixed those stations...

**Comment by maddavo** [comment]
Doing a search in the GM for stations may not be reliable.  It has been found in previous versions (not sure about the current version) that entering station names in the GM can bring up systems for which the entered station name does not exist as a station in the system.  To be sure that a station exists, one needs to look at the System View.

**Comment by SamMackrill** [comment]
Never seen that issue myself, always been spot on recently.
