### ISSUE TITLE
Improvement: Scrolling through filters on mobile opens filter lists

### ISSUE THREAD

**Issue by rster2002** [themroc5/eddb.io#173]
This is a minor annoyance, but when I'm on mobile and need to search for a station the filters are presented in a list. When I scroll through the filters, the inputs keep popping up causing the scrolling to sometimes stop. If this can be improved it would be great, but again is not that is doesn't work but it can be a bit annoying.

**Comment by rster2002** [comment]
Made a video trying to better describe the issue I'm having: https://youtu.be/ueKvv5o6gEI

In the video I'm trying to scroll like normal, but it seems that every time my finger starts the scroll from one of the input elements, it will incorrectly open.

**Comment by themroc5** [comment]
I totally understand this issue. And to be honest, I'm fully aware that the site is not perfectly optimized for smartphone screen sizes. Unfortunately I don't have the capacity to really solve those issues for good. At one point I might replace the select component and it is possible that other select components solve the scrolling issue altogether. Before that happens I can not do much though.

Sorry for that!

**Comment by rster2002** [comment]
Don't know if it's possible to contribute, but if I can I would be willing to look at it.

**Comment by themroc5** [comment]
You can contact me on Discord so we can have a chat about it. Currently I use Select 2 v3.5 and I believe the issue is that it does not detect a scrolling state and opens the UI regardless of the user scrolling down or not. I'm really not sure how to fix this properly tbh.

**Comment by rster2002** [comment]
Send you a message on discord. Let's continue there. Thanks for taking the time 👍

**Comment by themroc5** [comment]
Note: it's fixed now! Thanks for the help!
