### ISSUE TITLE
API - factions.json/factions.csv missing Home System for some factions

### ISSUE THREAD

**Issue by Jahfry** [themroc5/eddb.io#174]
Working on a project to collate systems that are available for PMF application. One thing I'd been trying to pull out of the data was whether a PMF in a specific system is native or not. 

To do that I need to know their home system. But a number of factions (player and non-player) have null entries for their home system in the EDDB API dumps. 

One example: "Escuadron Centinelas". Inara shows them as native to Catun. EDDB factions.json shows null. 

EDDB systems_populated.json does show them as in the system, but doesn't designate native status.

I'd guess a lot of the affected factions are fairly old? 

Not sure where Inara gets the native status from, or if maybe EDDB's data has it but is failing to put it in the factions dump. I suppose it's possible Inara is merging in data from player registered squadrons and not relying solely on FDev data. But I'm hoping the data is there where you can see it and it is just a dump bug. 

As far as I can find, EDDB is the only source that is giving access to the faction data in this manner? If there's an alternative source please let me know. Inara doesn't seem to provide System/Faction data in their API. I also looked on EDSM and didn't find it yesterday (can't confirm before filing this as EDSM's API is throwing 502 bad gateway errors atm). Having the data in a pre-made dump is actually ideal for my script anyway as I can make it self-contained in a client-side HTML form. 

If there's any chance of it being updated soon, great. If not it is still something I'd file for long term examination. For now I'll just display those as ? in my data and have people manually look at the system to confirm. 

Thanks!

**Comment by themroc5** [comment]
The Homesystem is not available in any API and is 100% manually updated. So it is no bug from my side. It is simply not made public from Frontier. Nothing I can do in this regard...
