### ISSUE TITLE
Update Contact details on main page (Discord invite, Quakenet reference)

### ISSUE THREAD

**Issue by Athanasius** [themroc5/eddb.io#184]
Just to ensure this doesn't get forgotten:

1. I made a channel-specific, permanent, Discord invite link: <https://discord.gg/d5g4VHe9pa> - so changing `Discord server: [EDCD](https://discord.gg/0uwCh6R62aQ0eeAX)` to link to that instead would help people not spam #general with what are #eddb questions.
2. The QuakeNet channel is all but dead.  Probably the only reasons people show up there are:
    1. The `IRC channel: [#eddb](https://kiwiirc.com/client/irc.quakenet.org/eddb) on [QuakeNet](https://www.quakenet.org/)` on the main page.
    2. the 'Chat' part of <https://edcodex.info/?m=tools&entry=53>
    
    so I'd suggest removing both.

**Comment by themroc5** [comment]
implemented, thanks @Athanasius!
