### ISSUE TITLE
Stations Missing Landing Pad Info page needs "has commodities" sort column

### ISSUE THREAD

**Issue by SnakeManPMC** [themroc5/eddb.io#21]
Stations Missing Landing Pad Info page needs "has commodities" sort column.

http://ross.eddb.io/station/snake-man

Currently it just allows us to sort by ID, system or station name. It would help greatly to make station searches more efficient if there would be way to sort only stations missing landing pad info AND which have existing commodities. It doesn't immediately help on trade route searches if we fix stations without any commodities.

**Comment by themroc5** [comment]
fixed
