### ISSUE TITLE
trade/single: set default values via get parameters

### ISSUE THREAD

**Issue by StalkR** [themroc5/eddb.io#24]
On http://eddb.io/trade/single we can choose system and station for origin and destination then press *Find routes*.
However when refreshing the page, those fields are back to empty. It would be nice if we could include them as GET parameters, so that we refreshing the page or using it as a bookmark, the fields are populated and all you need is to click *Find routes*.

Example of how such URL could look like: http://eddb.io/trade/single?osystem=Sol&ostation=Abraham+Lincoln&dsystem=Alpha+Centauri&dstation=Al-Din+Prospect

Once it is done, we can apply the same change to the station and systems page, which also contain the single hop finder form, and the multi hop trade route page for the origin system and station.

**Comment by themroc5** [comment]
look at a station page for examples
