### ISSUE TITLE
Find nearest station without landing pad or distance to star info from my location

### ISSUE THREAD

**Issue by SnakeManPMC** [themroc5/eddb.io#27]
Find nearest station without landing pad or distance to star info from my location.

The endless pursuit of adding station missing landing pad and distance to star information can be achieved from galaxy map without moving your own ship by hyperspace jumping. However many systems do not have system map available for all Cmdr's.

In EDDB you could add starting / current system location and it would then return the next closest system without this info, or perhaps it could return multi hop style if possible. But once you reach the system/station and add missing data, then you should be able to just "click one button" in EDDB to continue on the next one.

**Comment by themroc5** [comment]
done: http://ross.eddb.io/station/closest-missing
