### ISSUE TITLE
Update station indicates station already exists

### ISSUE THREAD

**Issue by bwcawman** [themroc5/eddb.io#28]
When attempting to update a station that has a similar name to an existing station the ROSS station update screen fails to update the station stating that it already exists.

For example. In the Saga system, Wiley Hub is too similar to Illy Hub. As a result, it is not possible to update the Wiley Hub information.

**Comment by themroc5** [comment]
Creating those station still have to be done manually due to the Levenshtein part. On updating such a manually created station, that check will not be performed if the user does not change the station name.

So fixed... :)

**Comment by bwcawman** [comment]
Dang, that was quick. Thanks.
