### ISSUE TITLE
Add "Has Resource Collection Site" and "In Conflict" to system information screen.

### ISSUE THREAD

**Issue by bwcawman** [themroc5/eddb.io#29]
It would be useful to be able to query for nearby systems that either have a resource collection site or are in conflict. This would make it easy for users to quickly find a place to go bounty hunting or simply go shoot down some other ships.

**Comment by Amunak** [comment]
Also, going with #30, it would be nice if we could at least fill in some very basic info like main star type (which incidentally also tells us if it is scoopable), and then perhaps the ability to fill in some other interesting system info. Like contains black holes / neutron stars / RESes / conflict zones / scoopable orbiting stars.

**Comment by themroc5** [comment]
merge with #30
