### ISSUE TITLE
Suggestion: Astronomical Bodies

### ISSUE THREAD

**Issue by Kitsune5010** [themroc5/eddb.io#30]
Any intentions to add the ability to add a list of planets, moons, belts and other astronomical bodies to the system view pages? As an avid explorer, I collect this information and would be eager to help fill it out.

**Comment by themroc5** [comment]
This could be very interesting indeed. I would wait though until we know what the API from the devs will offer. If we're lucky, we get that data :)

**Comment by Mikayex** [comment]
I'm also interested in having body's information (especially orbit parameters).
There is no news about API since a long time now... And I don't know if it will include astronomical data...
If it helps, I may develop this feature if you want.

**Comment by themroc5** [comment]
would you contact me on irc for this?

**Comment by themroc5** [comment]
done :)
