### ISSUE TITLE
too many market 'Y' => 'N' changes

### ISSUE THREAD

**Issue by maddavo** [themroc5/eddb.io#32]
I am trying to track down a data corrupting issue and I'm not sure it is coming from EDDB but there are a few indicators that seem to point to EDDB.  The problem is as follows:

I have noticed a large number of stations listed as market 'Y' changing to market 'N' - in bulk.  This I am seeing in my database.  I use the stations_lite.json to import data to my database from EDDB once a day.  The update time for the stations (over 200) seem to be within a minute from each other - the last batch I could identify was #16/04/2015 12:44:00# to #16/04/2015 12:45:00# .

Looking at a few stations in ROSS, I do indeed see that they are listed as Commodities = 'N'. I am not sure if this is because the 'N' value originates from EDDB OR if the value originates from the export from my database that EDDB imports.  HOWEVER when looking at the update history for a suspect station, I see many stations updated by @Snake_man with Commodities -> Y and yet the value displayed is 'N'.

This leads me to suspect that there is something wrong with the EDDB code.  An additional factor in is when I update the value again on ROSS then the Commodities displays as 'Y'.  This leads me to suspect that there may be something wrong with the INSERT station on ROSS rather than the UPDATE station.

Could you please check this and the data export stations_lite.json to verify that it is exporting the correct market='Y/N/?' value.  Thanks.

**Comment by themroc5** [comment]
You seem to import my `has_commodities` to your `market`. Why? My parameter is a vague paraemeter which reflects if we have price data or not. So with handling issue #21, I set alot of those to `FALSE`. I won't post-fix anything regarding this. Your `market` is different than my `has_commodities. That's it...

**Comment by maddavo** [comment]
I see, so your has_commodities value represents whether you have price data for a station rather than whether the station has commodities market.  What value then represents whether the station has a commodities market?

**Comment by themroc5** [comment]
Right now I don't have a discrete value for that. Imho that's not needed for now since it will clear out eventually with us collecting more data. In a couple of months we will almost have full data coverage I'm sure. With the steam release Elite Dangerous popularity doubled and so did eddb/ross usage.

**Comment by maddavo** [comment]
Ah, I see - OK.  We find it useful that the 'market' value tells us if there is a station that has a commodities market and we can at the same time see if we don't have prices for the station.  In that way we can easily find which stations we have to visit to collect prices.  As you say, it's about collecting data.

Is there any chance that you can add a commodities market value that represents whether the station has a commodities market?

Also, regarding the existing has_commodities field, it would seem that this then is an automatic eddb-generated value reliant upon whether you have prices data for that station.  Would it then be appropriate to change your station-editing page to NOT allow this value to be edited?  I think this is where some of the confusion may lie on its purpose because when we look at the system view of a station the field that you have is in the same section as other values that are editable such as rearm,refuel,repair,outfitting,shipyard.

**Comment by themroc5** [comment]
You are right. That's propably confusing for now. I left it open so people can set it to "no" if a station without an actual market received a false eddn update.

**Comment by themroc5** [comment]
see #33
