### ISSUE TITLE
Commodities header in wrong place.

### ISSUE THREAD

**Issue by finwen** [themroc5/eddb.io#36]
Happens for me both with Firefox and Chrome

A strange layout bug in ross
The commodities header stays at a fixed position.
If i scrolls up it can go up to hop finder section.
Seemns to be an odd bug if a system only has 1 commodities.

Works fine on stations with many commodities

Example station:  http://eddb.io/station/16880

![image](https://cloud.githubusercontent.com/assets/9721644/7317914/a422acf8-ea86-11e4-8dfb-115bf1b49599.png)

**Comment by themroc5** [comment]
fixed!
