### ISSUE TITLE
Suggestion: Feature the Gamification of ROSS by showing top editor stats on EDDB Homepage

### ISSUE THREAD

**Issue by AWMooreCO** [themroc5/eddb.io#37]
If you feature on the homepage of eddb.io your top ROSS editors of the Day/Week/Month/Year... and assign points (or show the # of changes made), it might encourage other non-ROSS-editing-EDDB users to take some time to edit systems and stations needing edited.

A few other "badges" or accolades that could be handed for for a given timeframe:
- Updating the oldest station information ("CmdrReynolds updated Station X, which hadn't been updated for 172 days!")
- Top Station Creators
- Top Station Editors
- Top System Editors
  etc.

Give people a game to play on EDDB alongside the E:D game, and you might find many happy — otherwise hidden — players.

-VictorSkali

**Comment by scott-dft** [comment]
+1 for this.
Just stumbled over the top contributors page and was surprised to see I had made the 160 spot. Thought that was rather good for me and renewed my interest in adding to EDDB. There is a steep rise in entries when you reach the top 50; kudos to them but yes to keep interest up having a ranking table over shorter time frames, last month, last quarter, etc. would help.

Scott

**Comment by themroc5** [comment]
Not necessary anymore due to EDDN.
