### ISSUE TITLE
Suggestion: Remove Imports/Exports from ROSS

### ISSUE THREAD

**Issue by AWMooreCO** [themroc5/eddb.io#38]
I'm not seeing any immediate benefit to having imports/exports be fillable options beyond getting any given station to 100%. The Imports/Exports have a tendency to change with regular to semi-regular frequency. Perhaps set them aside in an "Optional" section (where they don't affect a station's %-complete rating), or remove them altogether.

Prohibited Goods are helpful to have however.

-VictorSkali

**Comment by themroc5** [comment]
Some people might wanna add and view those information. It's less important than distance or pad. Still it belongs to Prohibited intel imho. And the complete-meter doesn't take that into account anyway...
