### ISSUE TITLE
Suggestion: Have ROSS fill in "Prohibited Goods" automatically based on Government Type

### ISSUE THREAD

**Issue by AWMooreCO** [themroc5/eddb.io#39]
Once a user sets a Government type on a Station, the "Prohibited Items" field should be automatically filled in by the system. If necessary, still allowing the editor to add or remove items. This could then be enhanced to update all stations missing Prohibited Items, if they have a Government set.

This will help EDDB users as long as EDDB recognizes that a Trade Hop Destination System has a prohibited item, and it will avoid showing that item in a result OR even more preferable, marking on the Trade Hop result that the item is Prohibited.

-VictorSkali

====

Partial List found from: https://www.youtube.com/watch?v=PZuYj9YsWfM

Anarchy:
Toxic Waste Only

Dictatorship:
Toxic Waste
Slaves

Feudal:
combat Stabilisers
Narcotics
Battle Weapons
Slaves
Toxic Waste

Communism:
Combat Stabilisers
Narcotics
Slaves
Toxic Waste
Imperial Slaves

Corporate:
Combat Stabilisers
Narcotics
Tobacco
Battle Weapons
Slaves
Toxic Waste
Imperial Slaves

Democracy:
Combat Stabilisers
Narcotics
Tobacco
Personal Weapons
Battle Weapons
Slaves
Toxic Waste
Imperial Slaves

Theocracy:
Combat Stabilisers
Narcotics
Tobacco
Personal Weapons
Battle Weapons
Consumer Technology
Slaves
Toxic Waste
Imperial Slaves

Cooperative:
Combat Stabilisers
Narcotics
Battle Weapons
Slaves
Toxic Waste
Imperial Slaves

Patronage:
Combat Stabilisers
Narcotics
Personal Weapons
Battle Weapons
Slaves
Toxic Waste

Confederacy:
Combat Stabilisers
Narcotics
Personal Weapons
Slaves
Toxic Waste
Imperial Slaves

Prison Colony:
Combat Stabilisers
Narcotics
Tobacco
Beer
Wine
Liquor
Personal Weapons
Battle Weapons
Consumer Technology
Slaves
Toxic Waste
Imperial Slaves

**Comment by themroc5** [comment]
That sounds interesting. I'd need 100% certainty that this works. Sometimes I've seen rare commodities prohibited. Those are missing in the upper list...

**Comment by Brokenstorm** [comment]
Station allegiance also affect the legality of some goods in Corporate (Personal Weapons, Imperial Slaves), Democracy (Tobacco), Dictatorship (Imperial Slaves), Patronage (Imperial Slaves) and Theocracy (Beer, Wine, Liquor).

**Comment by themroc5** [comment]
This isn't possible due to Powers
