### ISSUE TITLE
Suggestion: Add "Report This [Station/System]" to ROSS

### ISSUE THREAD

**Issue by AWMooreCO** [themroc5/eddb.io#40]
In the event of incorrect systems or stations that the average ROSS editor can't delete or remove, perhaps a "report this system" button might be in order, which on clicking the user could add a reason why it should be removed, and then send it off to a queue accessible to any user with removal privileges.

Might improve the workflow of many newer editors.

-VictorSkali

**Comment by themroc5** [comment]
agreed

**Comment by themroc5** [comment]
we have 100% station coverage and sync systems with EDSM. So that's not needed anymore.
