### ISSUE TITLE
Suggestion: Make it easier to find and route Rare Commodities

### ISSUE THREAD

**Issue by AWMooreCO** [themroc5/eddb.io#41]
It could be incredibly beneficial to have a toggle in the Single and Multi-Hop screens to trade "only in," "primarily in," or "prefer to/periodically in" rare commodities. It would beat having to rely on forum posts to find rare goods such as this one: https://forums.frontier.co.uk/showthread.php?t=63119

Also perhaps it might be good to have these rare goods show up on the Commodities page? (e.g., Sanuma Decorative Meat, Waters of Shintara, Rapa Bao Snake Skins, Lucan Onion Head, etc.)

**Comment by themroc5** [comment]
The database schema is prepared for rares already. 
I could add a new section to ROSS for adding and editing rare commodities. 

As an alternative I could just import a list. If anyone would provide one, that feature could be implemented pretty soon. Especially the category is not listed anywhere and would be nice to have...

**Comment by AWMooreCO** [comment]
@themroc5  Looks like you can get a current list of rare items from this spreadsheet: http://www.mediafire.com/download/cbta7oaccm05ypa/ED_RareGoods_SystemsDistance_rev1380.xlsx

**Comment by mEDI-S** [comment]
a cvs list but it's not all right 
https://github.com/mEDI-S/mEDI_s-Elite-Tools/blob/master/db/rares.csv

and this is a experimental rarerouter finder example
https://github.com/mEDI-S/mEDI_s-Elite-Tools/blob/master/rareroute.py

mEDI

**Comment by libbkmz** [comment]
This one is the best, AFAIK https://docs.google.com/spreadsheets/d/17Zv55yEjVdHrNzkH7BPnTCtXRs8GDHqchYjo9Svkyh4/export?format=csv

**Comment by themroc5** [comment]
Rares pretty much lost importance by now and many resources on the web provide necessary informtion already.
