### ISSUE TITLE
Suggestion: Ship and Module locations

### ISSUE THREAD

**Issue by snoopy82481** [themroc5/eddb.io#44]
I know it would probably be an increase to the database load, but a way to get the information for where modules and ships are located would be an immense help.  Instead of having to peruse tons of forum posts and wikis for the information cmdrs could input them into the database through the tool of their choice.maybe even OCR could be used for it but since that is a separate tool I would make the suggestion to the developer on getting that updated.

**Comment by cmmcleod** [comment]
I believe this can be closed :)

**Comment by themroc5** [comment]
oh yes!
