### ISSUE TITLE
Add rare flag in JSON export for commodities

### ISSUE THREAD

**Issue by AnthorNet** [themroc5/eddb.io#46]

**Comment by themroc5** [comment]
that's gonna be implemented in the next next API version v4

**Comment by Tricky1702** [comment]
Whilst your at it, I suggest an illegal flag too. Some rares and commodities aren't listed in the prohibited section of a station but are illegal.

**Comment by themroc5** [comment]
Ok @AnthorNet I added it just now :)
@Tricky1702 Unfortunately I don't have that data available. Afaik in Anarchy systems nothing is illegal?
