### ISSUE TITLE
loop fix

### ISSUE THREAD

**Issue by themroc5** [themroc5/eddb.io#50]
[11:57:50] <Wartface> discovered a profitable loop route which is generating 2.4k but I cannot get it to show in the Loop Route Finder.  Fiennes Vision (HR 8170) Resonating Separators to Crichton City (Hu Jona) and Gold back.

**Comment by Wartface** [comment]
Here's screenies of the single route showing the profit each way (1k plus 1.4k).  Third screenshot is of the Loop with specific filters which doesn't show the same route.  Removing the Implicit Items still doesn't list the items.

![route_single](https://cloud.githubusercontent.com/assets/12559510/7770084/40773356-0082-11e5-9ccf-e2af18d63640.png)

![route_single_2](https://cloud.githubusercontent.com/assets/12559510/7770102/8d737552-0082-11e5-8317-5d4ac477443c.png)

![route_loop](https://cloud.githubusercontent.com/assets/12559510/7770104/91549084-0082-11e5-85c4-c79764fd2e1a.png)

HTH

**Comment by themroc5** [comment]
I only consider station with max 1000ls distance to spawn point as reasonable. Crichton City has 16312 ls, so that gets ignored automatically.
