### ISSUE TITLE
Suggestion: Allow trade route searches based on only System name

### ISSUE THREAD

**Issue by trmoody-gh** [themroc5/eddb.io#52]
The ability to generate trade routes based on just a source system would be useful for spotting cheeky opportunities that may only be a short distance away.

**Comment by themroc5** [comment]
you mean trade roots in one system between two stations?

**Comment by trmoody-gh** [comment]
No sir, instead I propose a scan of all known stations in the given system, taking the minimum price of each commodity and then searching for remote systems in which to sell.

On 25 May 2015 18:10:50 BST, Paul Heisig <notifications@github.com> wrote:
>you mean trade roots in one system between two stations?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/themroc5/eddb.io/issues/52#issuecomment-105271596

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by themroc5** [comment]
That's possible in the single route finder already. You can leave the station blank...

**Comment by trmoody-gh** [comment]
Ahh, I see. Yet for Dyaushibi it is not the case

**Comment by themroc5** [comment]
I don't get it. I go to http://eddb.io/trade/single ... set Dyaushibi in Origin System and click Find routes

**Comment by trmoody-gh** [comment]
I did, and got no result, which is why I thought the suggestion was required.
I've since set the max hop and max station distances to 0, and it returns a result. The previous values were not too low that nothing should have appeared though.
If it behaves strange again I'll confirm the parameters.
Sorry for a non-suggestion.

**Comment by themroc5** [comment]
no prob :)
