### ISSUE TITLE
Suggestion: 'Not' (or 'Select All') option for populating the 'Commodity Filter' of a route search.

### ISSUE THREAD

**Issue by trmoody-gh** [themroc5/eddb.io#53]
It would very useful to be able to more easily exclude certain commodities from the list when doing searches.

Often I find it is the case that something like 'Imperial Slaves' will be the only commodity for which routes are returned, but all of the destination stations usually have very outdated prices. When I get there I would be earning a loss on the trade (if I sell there).

I have learnt to add all commodities to the filter and then remove Imperial Slaves (for example) before searching for routes after the first try gives the above scenario.

It would make life easier if all of the commodities could be added to the filter in one click, or to use NOT logic on the filter, whichever is deemed less confusing.

**Comment by wiz0floyd** [comment]
Since loop search has an "ignored commodities" selection, could it be ported to the other searches?

**Comment by themroc5** [comment]
yes. soon!

**Comment by themroc5** [comment]
done with the current single route finder
