### ISSUE TITLE
Missing Wares after 1.3 update

### ISSUE THREAD

**Issue by jurrehart** [themroc5/eddb.io#61]
Here are some missing wares after the 1.3 update:
 *  Sap 8 Core Container
 * Osmium

**Comment by themroc5** [comment]
I'm on vacation until next friday and will add them as soon as I'm back!

**Comment by lemmy04** [comment]
There's also another new rare but I've seen it only in the list of illegal items at some stations: Trinkets of hidden fortune

**Comment by themroc5** [comment]
added
