### ISSUE TITLE
Suggestion: Station last updated listing

### ISSUE THREAD

**Issue by meridias** [themroc5/eddb.io#62]
Not sure how easy it would be to generate a page from the database that lists the stations (up to a certain amount) by how long it's been since it had an update. Filterable maybe by range, but definately should be sortable by how recent. Just in case those of us out exploring come across a station that hasn't been updated in awhile. Possibilities could be all stations in a certain range or x number of stations that haven't been updated in x days.

**Comment by themroc5** [comment]
Are you talking about price updates? We don't even have 100% station price coverage. The list would end up in houndreds or thousends of stations with 200-300 days old data :)

**Comment by meridias** [comment]
On the 'Find commodity' page, there's already a column for 'last updated' for a station but that list is filtered by a specific commodity. What I'm suggesting is use that data that's already there and generate a page that shows the stations and their last updated status in a let's say 30 LY range from a given system.
ie. I'm in the LHS 3447 system and I'm interested in helping update station listings in my general area. I look at the list I'm suggesting and see that (for example) the Duke City station in Clayakarma system hasn't been updated in 69 days. I head over there, do my thing, boom updated.
Instead of having to use the 'find commodity' page and worry about what station is carrying which goods, I could just use the station page and get a list of all of them.
