### ISSUE TITLE
Feature Request: Auto-fill Target System in Single Hop

### ISSUE THREAD

**Issue by scott-dft** [themroc5/eddb.io#63]
At the moment the only time I have to go back to my keyboard (those odd occasions when I'm not ROSSing of course :-P) is when I have a target system (which I can never remember/ spell correctly) to input (the current system I can copy-paste from ED:Discovery). If I have put in the Origin System and the max jump is there then your very clever system would I'm sure be able to work out the nearest available systems from origin.
It would be great if the Target System had its drop-down box, when there is no text entered, have these (or at least the closest 6 or 10) systems listed ready to pick. Obviously if the user starts to put in specific text then current text match routine takes over.

Without the ability to copy System names from E:D galaxy map; this extra feature would be real helpful.

Cheers,
Scott

**Comment by themroc5** [comment]
This would require more work than you might imagine. I'm having plenty of other pretty important features to build first, so this one might end up being not implemented.

**Comment by caiodias** [comment]
@themroc5 I can try to help. I'm developer too.
