### ISSUE TITLE
Bug: Web System info and systems.json don't match

### ISSUE THREAD

**Issue by Slugsie** [themroc5/eddb.io#65]
I'm writing an app that uses the systems.json and stations_lite.json dumps from the EDDB. I've noticed that the data in the JSON files doesn't always match the information presented on the web page. For instance the Carang Hut system is listed as having a faction of 'Alliance League' in the systems.json file (downloaded today, so current), yet the website lists it as being Kan Aphu Prison Colony (http://ross.eddb.io/system/update/2885) The only faction operating in the system at the station is indeed the Kan Aphu Prison Colony. A further question however is, do systems even have a faction?

**Comment by themroc5** [comment]
Hi,

the JSON is only being dumped nightly, so updates during the day will 
not be in there before the dump is being done.
Yes, there is one faction that "controls" the system. It obviously is 
one that rules one or more stations.

Best
Pul

------ Originalnachricht ------
Von: "Slugsie" <notifications@github.com>
An: "themroc5/eddb.io" <eddb.io@noreply.github.com>
Gesendet: 10.10.2015 19:37:04
Betreff: [eddb.io] Bug: Web System info and systems.json don't match 
(#65)

**Comment by Mikayex** [comment]
Furthermore, I just checked Carang Hut system in systems.json and faction is Kan Aphu Prison Colony, so this is coherent with the website.

**Comment by Slugsie** [comment]
Very odd, the systems.json file that I had that was updated about 14 hours ago was wrong then, but I didn't see anything on ROSS that suggested the system had been updated. Seems bizarre that I just randomly chose the one that was wrong, but that's what happened apparently.

Where in game does it show which faction controls a system? I can see the information for stations, but not for systems.

**Comment by themroc5** [comment]
eddb imports from many sources and those changes sometimes can be alot. The ROSS history only shows manual data changed. Be assured that the JSONs always reflect the data the moment they're created.

In game: Just move the cursor with WASD to unselect any body/station. Thats the system intel :)

**Comment by Mikayex** [comment]
In the galaxy map, you can see the main faction (on the popup of the system if I remember)
