### ISSUE TITLE
Feature Request: Pre-Defined Route

### ISSUE THREAD

**Issue by denali1** [themroc5/eddb.io#73]
Single Route, expanded.  For those who have created a rare trading route, but want to throw in other commodities to maximize profit.  For example, I run a rare route from Rajukru > AZ Cancri > 39 Tauri > George Pantazis > Altair > HIP 80364 Rajukru.  I'd like to be able to put those in one screen and have it tell me the best commodities to carry from one station to the other on one screen.  For now, I have to do it one stop at a time using the One Hop feature.

**Comment by themroc5** [comment]
Have a look at the new Trade Along The Way feature of the [Multi Hop Trade Route Finder](https://eddb.io/trade/hops) :)
