### ISSUE TITLE
Multi Hop Traderoute has some issues with showing the result correctly

### ISSUE THREAD

**Issue by muthan** [themroc5/eddb.io#75]
I just uses the Multi Hop Trade Route Tool and it seems that in the results it doesn't show the destination of the first trade correctly. 

Also it has some difficulty to show the last one correctly. But when you load more the trade route shows now correctly but the new last one has the problem.

**Comment by themroc5** [comment]
Sorry I don't follow. It looks correct to me. One box is one station and in the first you only buy. In the 2nd you sell and buy again. In the last you only sell :)

**Comment by muthan** [comment]
my bad. you're right, i was irritated about the fact that each station is it's own box and thought they were start and destination. And I don't realy know why. 
Probably because I used mostly the Loop tool and there it is different.

But nevermind then. keep up the great work.
