### ISSUE TITLE
Suggestion: Full system minor faction list.

### ISSUE THREAD

**Issue by Tricky1702** [themroc5/eddb.io#78]
The only minor faction information in eddb at the moment is just limited to the ones owning a station/outpost.

What I am suggesting is a full list of all minor factions in the system, along with player owned, major faction allegiance, government, influence and state. This information could be picked up by players who have a minor faction in game to help them gain an understanding of their surrounding area.

Of course the information would be a snapshot and not real time, but it would be advantageous to be in now for when an API is developed.

**Comment by adam6806** [comment]
Yes please this would be fantastic!

**Comment by themroc5** [comment]
Finally did this :)
