### ISSUE TITLE
Special page for station search for missing market price and distance from star data

### ISSUE THREAD

**Issue by SnakeManPMC** [themroc5/eddb.io#80]
At Jan 2016 there still are many stations with markets but no CMDR's have sent market price data to EDDN, we need to correct this. We need a special page for searching these.

Station missing market prices or distance from star data, how would it work:

1) input your current system
2) select landing pad size filter (for example large pads only)
3) select max distance from star (for example nobody trades beyond 1000ls stations so no point updating those)

Click search and it would return list of closest systems + stations matching search filters.

On part 3 it would by default return stations with missing distance from star data, the limit would only cap those crazy hutton orbital type stations where nobody would be trading.

Reference Maddavo's editstation page: http://www.davek.com.au/td/editstation.asp

**Comment by djadjok** [comment]
I think that  I've already posted same kind of suggestion, so count me in. May be as a quick solution a little extension to existing helper page (stations with distances omitted) can be sufficient.
