### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ElGarden** [themroc5/eddb.io#81]
i use multi hope, and there it is:  Huygens Enterprise   Adityan  51 days  148,060 ls  Pad: L
 Buy: 36 ×  Superconductors for 6,743 Cr      Supply: 318,753
51.96 ly
 Blaauw Hub   Tenche  65 days  40,347 ls  Pad: L
 Sell: 36 ×  Superconductors for 7,519 Cr ,                I bought 36 superconductors, flew to the station and found that there they are bought at a lower price that I bought, a total of: I'm FUCKING LOST 6.300 credits FKING THANK U

**Comment by cmmcleod** [comment]
Well the prices for those stations hadn't been updated in almost 2 months... So it's not really a bug, just unfortunate.

**Comment by themroc5** [comment]
I'm sorry for your loss.

EDDB is a community driven website. Almost every information is user created. You can look [here](https://ross.eddb.io/history) and [here](https://ross.eddb.io/eddn/log) to get an idea of that process. To prevent a credits loss, you could set a Price Age filter. Then, chance will be higher that the prices you see on EDDB are correct.
