### ISSUE TITLE
Multi hop and Loop trade route additonal filter.

### ISSUE THREAD

**Issue by Zeolish** [themroc5/eddb.io#83]
Would it be possible to add a filter to the trade route options?

The filter is basically an filter on distance from star to station.
![image](https://cloud.githubusercontent.com/assets/9748831/12331943/d47f734e-bae3-11e5-8aa2-d8e3983f1ea4.png)
I have circled the info i mean.
It may seem trivial but choosing a system with a shorter travel distance from the star at both ends would be better than one that takes longer but the profit is 100cr more per tonne.

If you need me to elaborate please ask questions. I think adding this filter would help narrow down loop routes to find a faster one as Time is money! 

sorry if this is a repost but i couldnt find this request.

CMDR Zeoli.

**Comment by themroc5** [comment]
This is implemented already in the station filter as "Distance". Please confirm that this is what you mean.

**Comment by Zeolish** [comment]
Hi @themroc5,

![image](https://cloud.githubusercontent.com/assets/9748831/12335133/94a442ce-baf5-11e5-938a-9d397271df61.png)

I mean the ones underlined. the Distance i believe is the distance between the star systems and not between the star and station.

thanks.

**Comment by Zeolish** [comment]
So sorry. really didnt see that filter. cant believe it lol. thanks.

**Comment by themroc5** [comment]
No problem :) Enjoy!
