### ISSUE TITLE
can't get market date (Keyes Retreat)

### ISSUE THREAD

**Issue by gopher34** [themroc5/eddb.io#86]
Don't know if this is the right place to report a small bug which involves failed price update, but anyway.... System LTT 1581 , Station Keyes Retreat. Something is wrong with updating price at this station. EDMarketConnector says that it "Can't get market data!". I checked another stations and it updates prices right. I tried reloging, tried relaunching EDMC program - still the same problem. I have the latest version of EDMarketConnector.

**Comment by Marginal** [comment]
See https://github.com/Marginal/EDMarketConnector/issues/6

**Comment by themroc5** [comment]
exactly
