### ISSUE TITLE
Quick Price Update

### ISSUE THREAD

**Issue by nyansen** [themroc5/eddb.io#9]
A feature to Update Prices for one Item.

Example:
Fish from Foo to Bar
Buy in Foo for 245 
Sell in Bar for 356
But ingame I buy it for 256 and Sell it for 376.

Now I have to make a Screen and update it to EDDN. But It will be easier to update only this Item on the Page for both Stations.

**Comment by themroc5** [comment]
EDDN is the way to update price data. So everybody benefits...
