### ISSUE TITLE
Prices are Incorrect

### ISSUE THREAD

**Issue by ColonelBBB** [themroc5/eddb.io#95]
Hiya, been a user for a few weeks a great tool, especially as I can't devote the time needed. It's usually been there or abouts on prices, however today I'm finding the prices are close to 50% out, thought you should know. I don't know if it's relevant but I'm on elite dangerous for xbox.

**Comment by themroc5** [comment]
Prices are 100% community driven. EDDB is only a platform for people feeding it with correct data. If you're worried about old data, just limit the price ago to 2 days or so...

Unfortunately XB1 users can't use Frontiers API to use EDMC to feed EDDN to eventually feed EDDB...
