### ISSUE TITLE
New Module: Corrosion Resistant Cargo Racks

### ISSUE THREAD

**Issue by Kitsune5010** [themroc5/eddb.io#97]
Palin Research Centre in Maia offers Corrosion Resistant Cargo Racks for outfitting (not an Engineer mod as many previously thought).

A friend reported this via EDMC through the EDDN network, but it does not seem to have been picked up by EDDB or other sites.

**Comment by Marginal** [comment]
We need your friend (or someone else with access to Palin Research Centre) to visit it, run EDMC [from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source) and post the .json file that EDMC writes in its `dump` subfolder here.

A screenshot of the module from the outfitting screen would be handy too.

**Comment by Kitsune5010** [comment]
Here's the JSON of his current outfit, which contains the second size of cargo rack.
[last.txt](https://github.com/themroc5/eddb.io/files/322072/last.txt)

In addition, he converted the specific entry into XML for viewing:

<Object name="Slot08_Size3">
                    <Object name="module">
                        <value key="id" value="128681992"></value>
                        <value key="name" value="Int_CorrosionProofCargoRack_Size1_Class2"></value>
                        <value key="value" value="12249"></value>
                        <value key="unloaned" value=","></value>
                        <value key="free" value="false"></value>
                        <value key="health" value="1000000"></value>
                        <value key="on" value="true"></value>
                        <value key="priority" value="1"></value>
                        <Object name="ammo">
                            <value key="clip" value=","></value></Object></Object></Object>

There is another size, Cargo Rack Size 1 Class 1.

**Comment by Marginal** [comment]
EDMC 2.15 now reports these to EDDN correctly

**Comment by Kitsune5010** [comment]
Looks like everything has been working for awhile - I just haven't come back around in a bit and didn't notice this was still open!

**Comment by themroc5** [comment]
indeed :)
